### ISSUE TITLE
State is mutated

### ISSUE THREAD

**Issue by jakallergis** [BenBrewerBowman/react-use-object-state#4]
Hi Ben! Nice library.

Quick question. I think this line of code [here](https://github.com/BenBrewerBowman/react-use-object-state/blob/16a61ad5fed20c3354d1497d79d68e4c8385c741/src/array/array.reducers.ts#L46) is mutating state.

What do you think?

**Comment by BenBrewerBowman** [comment]
Haha thanks! And yes good catch! I def should not be mutating state. I
think I might have been lazy at the time (bc theoretically it should still
work in this case) and forgot to update it with a solution that doesn’t
mutate. Thanks for the
heads up! I’ll fix it!

**Comment by jakallergis** [comment]
Awesome! Thanks!
