### ISSUE TITLE
Cannot find module on React Native

### ISSUE THREAD

**Issue by josegoval** [BenBrewerBowman/react-use-object-state#7]
Got this error on React Native:

```
import {useBooleanState} from 'react-use-object-state';
//_Cannot find module 'react-use-object-state' or its corresponding type declarations._
```

Is it usable on React Native?

**Comment by BenBrewerBowman** [comment]
@josegoval i am not sure why it wouldn't be usable since it's really just built on top of react. I'll setup a react-native app and check it out. I'll let you know what I find out. Thanks for reaching out!

**Comment by BenBrewerBowman** [comment]
@josegoval I accidentally published a bad package last time and it could not find the index at the root of the module. I published a new version that seems to be working. I tested it out in CRNA and expo and it seems to be working just fine. Bump this package to the latest version and you should be good to go. 

Let me know if you have any further issues and I'll fix them ASAP. Also feel free to reach out with any feedback, thoughts, ideas, or suggestions. 

Thanks!
Ben
